
fastlane_version "2.80.0"

####################
# BEFORE
####################

before_all do
end

####################
# PUBLIC LANES
####################

desc "Resolve all dependencies"
lane :dependencies do
  carthage(
    command: "bootstrap",
    cache_builds: true
  )
end

desc "Run tests for iOS"
lane :test_ios do
  reset_simulators if is_ci?
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-iOS"
  )
end

desc "Run tests for tvOS"
lane :test_tvos do
  reset_simulators if is_ci?
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-tvOS"
  )
end

desc "Run tests for MacOS"
lane :test_macos do
  reset_simulators if is_ci?
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-macOS",
    destination: "platform=macOS"
  )
end

desc "Run tests for Watch OS"
lane :test_watchos do
  xcodebuild(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-watchOS"
  )
end

####################
# PRIVATE LANES
####################
