
fastlane_version "2.91.0"

####################
# BEFORE
####################

before_all do
end

####################
# PUBLIC LANES
####################

desc "Resolve all dependencies"
lane :dependencies do
  carthage(
    command: "bootstrap",
    cache_builds: true
  )
end

desc "Update all dependencies"
lane :update_dependencies do
  carthage(
    command: "update",
    cache_builds: true
  )
end

desc "Run Podspec Linting"
lane :lint_podspec do
  pod_lib_lint(
    verbose: true,
    allow_warnings: true
  )
end

desc "Deploy Pod"
lane :deploy_pod do
  pod_push(
    verbose: true
  )
end

desc "Run all pre-build checks"
lane :check do
  swiftlint(
    output_file: ENV["LOCAL_OUTPUT_DIR"] + "/swiftlint-results.html",
    reporter: "html"
  )
end

desc "Run all the unit tests"
lane :test do
  reset_simulators if is_ci?
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-iOS"
  )
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-tvOS"
  )
  scan(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-macOS",
    destination: "platform=macOS"
  )
  build_watchos
end

desc "Generate docs"
lane :generate_docs do
  jazzy
end

####################
# PRIVATE LANES
####################

desc "Build the Watch OS scheme"
private_lane :build_watchos do
  xcodebuild(
    workspace: "NanoLog.xcworkspace",
    scheme: "NanoLog-watchOS"
  )
end
